name: CI_$(date:yyyyMMdd)$(rev:.r)

# Re-enable trigger once Full build not deploying every time
trigger: none
#trigger:
#  paths:
#    exclude:
#    - SpotifyRecordCollection.Deployment/*
#    - .gitignore
#    - Full.yaml
#    - README.md

pool:
  vmImage: 'windows-latest'

variables:
  clientAppPath: 'spotify-record-collection'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: ClientApp
    steps:
    - task: NodeTool@0
      displayName: 'Ensure Node Installed'
      inputs:
        versionSpec: '12.x'
    - task: Npm@1
      displayName: 'Install ClientApp packages'
      inputs:
        command: 'install'
        workingDir: $(clientAppPath)        
    - task: Npm@1
      displayName: 'Build ClientApp'
      inputs:
        command: 'custom'
        workingDir: $(clientAppPath)
        customCommand: 'run build'